apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: moodle
  name: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      run: moodle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: moodle
    spec:
      containers:
      - env:
        - name: MOODLE_URL
          value: http://localhost:8080
        - name: MOODLE_DB_HOST
          value: moodledb
        image: xflin/moodle:3.5
        imagePullPolicy: IfNotPresent
        name: moodle
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
