apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: moodle
  name: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      run: moodle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: moodle
    spec:
      containers:
      - env:
        - name: MOODLE_DB_TYPE
          value: mysqli
        - name: MOODLE_DB_HOST
          value: moodledb
        - name: MOODLE_DB_PORT
          value: 3306
        - name: MOODLE_DB_NAME
          value: moodle
        - name: MOODLE_DB_USER
          value: moodle
        - name: MOODLE_DB_PASS
          value: moodle
        - name: MOODLE_URL
          value: http://localhost:8080
        image: moodle:3.5
        imagePullPolicy: IfNotPresent
        name: moodle
        ports:
        - containerPort: 80
          protocol: TCP
